### PR TITLE
fix: bug#340

### PR DESCRIPTION
**Pull request by FilipePfluck**
## Description

The library would always use `encodeURI` or `encodeURIComponent`. 

This should allow users to have more freedom in specifying how URLs get encoded, rather than trying to adjust this library's default behavior to account for every edge case.

I added a test in the test-buildURL.js

## Checklist

- [x] Read the [contributing guidelines](CONTRIBUTING.md).
- [x] Each commit follows the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) spec format.
- [x] Update the readme (if applicable).
- [x] Update or add any necessary API documentation (if applicable)
- [x] All existing unit tests are still passing (if applicable).

- [x] Add some [steps](#steps-to-test) so we can test your bug fix or feature (if applicable).
- [x] Add new passing unit tests to cover the code introduced by your PR (if applicable).
- [ ] Any breaking changes are specified on the commit on which they are introduced with `BREAKING CHANGE` in the body of the commit.
- [ ] If this is a big feature with breaking changes, consider opening an issue to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.

### CODE REVIEW

**Review by luqven — CHANGES_REQUESTED** [review]
Thanks again for taking the time to help us tackle this issue. This is a great start!

Reading over your PR, I've realized that I think we need to refactor how we handle `options` in `buildURL` and `_sanitizePath`. When we added support for `disablePathEncoding` we also decided to pass this option to `this._sanitizePath` as `{encode}`.

```js
  buildURL(rawPath = '', params = {}, options = {}) {
    const path = this._sanitizePath(rawPath, {
      encode: !options.disablePathEncoding
    });
```

This was a mistake. I think it makes future maintenance more difficult and risks decoupling `encoding` from `options`. Moreover, now that we want to support the custom encoding function, having `encode` and `encoder` values in the `options` object could get confusing.

This means is that we should change lines 51-54 to read:

```js
const path = this._sanitizePath(rawPath, options)
```

This way, `options` is passed directly to `this._sanitizePath`.

This also means that later, in `_santizePath` we should reference the new `options` values:

```js
 _sanitizePath(path, options = {}) {
    // Strip leading slash first (we'll re-add after encoding)
    let _path = path.replace(/^\//, '');

    if (options.disablePathEncoding) {
      return '/' + _path;
    }

    if (options.encoder) {
      _path = options.encoder(_path);
    } else if (/^https?:\/\//.test(_path)) {
      // Use de/encodeURIComponent to ensure *all* characters are handled,
      // since it's being used as a path
      _path = encodeURIComponent(_path);
    } else {
      // Use de/encodeURI if we think the path is just a path,
      // so it leaves legal characters like '/' and '@' alone
      _path = encodeURI(_path).replace(/[#?:+]/g, encodeURIComponent);
    }
    return '/' + _path;
  }
```

So concretely, I think we need to:
1. rename the custom encoding function to `encoder`
2. refactor the way we pass options to `this._santizePath` in [buildURL](https://github.com/FilipePfluck/js-core/blob/e4d46604bcb9def0b740405d1d787b9c0924902e/src/index.js#L51-L54)
3. change [_santizePath](https://github.com/FilipePfluck/js-core/blob/e4d46604bcb9def0b740405d1d787b9c0924902e/src/index.js#L161-L182) to reference `options.disablePathEncoding` and not `encode`
4. update the srcset [changes](https://github.com/FilipePfluck/js-core/blob/e4d46604bcb9def0b740405d1d787b9c0924902e/src/index.js#L305) so they pass in `options` and not `{options.disablePathEncoding, options.customEncoder}`.

These are some significant changes and I want to be respectful of your time. To that end, if you feel at any time that you'd rather hand off the work, you can always grant us push permissions to your fork and we can help with some of these changes.

As always let us know if you have any questions and we'll get back to you soon as we can.

Thanks again for the awesome work on this!

**Comment by FilipePfluck** [comment]
Saw the request changes, I will work on this.

**Comment by FilipePfluck** [comment]
Hey, I think I fixed everything you guys suggested. If there's still something for me to do, let me know.

**Comment by FilipePfluck** [comment]
Hey @luqven Just reminding if you didn't noticed, I updated the readme

**Review by luqven — CHANGES_REQUESTED** [review]
Hey @FilipePfluck ,

Sorry for the delay here. I noticed you still have the 3 `/dist` [changes](https://github.com/imgix/js-core/pull/343/files#r997676143) checked into this PR. Could you unstage those changes? If it's easier to open up a new PR without those changes that's fine as well.

Until we remove the `/dist` files from the PR I don't think we'll be able to get this merged in.

**Comment by FilipePfluck** [comment]
Hey @luqven sorry for having those dist files again. I thought I removed them, but they're generated automatically, right? Perhaps I generated them again in my previous commit and didn't notice. I think that know everything is right.

**Comment by luqven** [comment]
Hey @FilipePfluck, sorry I should have been clearer here.

My expectation wasn't that you delete the dist files but rather that you revert the changes made to those files.

Anytime you run our `build` or `test` scripts, you'll likely update those files. But we don't stage those changes to our commits because our automated release process does it for us. Before we cut a new release, it updates the `/dist` folder. Our contributing guide could be clearer on this point.

I know that you've put a lot of work into this already, so I'd be more than happy to revert these myself if you grant me push permissions to your fork. Otherwise, if you feel up to it, you can [revert](https://dev.to/lofiandcode/git-and-github-how-to-revert-a-single-file-dha) those files to the state their in on the `main` branch.

Once you've done that, we should be able to merge this in.

If anything about this is unclear, please don't hesitate to reach out!

**Comment by FilipePfluck** [comment]
@luqven  Now I understand what you meant, I just added everything with ```git add .```, and I shouldn't have added them. Anyway, I added you as a collaborator to my fork, so feel free to revert this the way you think suits better.

**Comment by luqven** [comment]
Updated the branch to rollback the changes to `dist/` and updated commit messages to match conventional commit specs.

Just confirming we don't need any additional tests here and we should be good to go.

**Comment by FilipePfluck** [comment]
Hey @luqven do we have any news about this PR? I don't mean to hurry, but if possible, I'd like to get this PR merged today, as it is the last day of october. I want to be respectful to your time as you were to mine, so if there's anything left for me to do let me know. :)

**Comment by luqven** [comment]
> Hey @luqven do we have any news about this PR? I don't mean to hurry, but if possible, I'd like to get this PR merged today, as it is the last day of october. I want to be respectful to your time as you were to mine, so if there's anything left for me to do let me know. :)

Merging in today. Apols for delay!

**Comment by sherwinski** [comment]
Thanks for all of your hard work on this @FilipePfluck !

**Pull request merged**
