### PR TITLE
build: drop module type from package.json

### PR DESCRIPTION
**Pull request by ericdeansanchez**

### CODE REVIEW

**Review by frederickfogerty — COMMENTED** [review]
I'll reply more tomorrow, but I'm not sure this is the _best_ solution. I think maybe we could change the `browser` field to not point to the UMD bundle as well 🤷

**Comment by ericdeansanchez** [comment]
@frederickfogerty Okay, cool I'll hold off.

**Comment by ericdeansanchez** [comment]
Considering closing this in favor of #260

**Comment by frederickfogerty** [comment]
Yeah I think we should close this 👍

**Pull request closed without merging**
